"""Stock report schema."""

# --- generated by schemagen 2.4, do not edit ---
FIELDS = (
    ("id", "integer", False),
    ("sku", "string", False),
    ("warehouse", "string", False),
    ("quantity", "integer", False),
    ("reserved", "integer", True),
    ("updated_at", "timestamp", False),
)
FIELD_NAMES = tuple(name for name, _, _ in FIELDS)
NULLABLE = frozenset(name for name, _, nullable in FIELDS if nullable)
# --- end generated ---


def stock_level(row):
    return row["quantity"] - (row["reserved"] or 0)
