name: jscpd CI

on: [push, pull_request]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x, 26.x]

    steps:
    - uses: actions/checkout@v5
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: pnpm install

    - name: Build
      run: pnpm build

    - name: Lint
      run: pnpm lint

    - name: Test
      run: pnpm test

    - name: jscpd
      run: ./apps/jscpd/bin/jscpd ./fixtures
